server {
    listen 80;
    root /usr/share/nginx/html;
    absolute_redirect off;

    location = / {
        return 302 /pages/homepage/homepage.html;
    }

    location / {
        try_files $uri $uri/ =404;
        add_header Cache-Control "no-store";
    }
}
